# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f974f844fe078e9998ba285f57a4ee4fcf8301903c069c776852429c54b4f649fe6c3698178989fc54f9dd31017905ef0d8e046d42eb1b8ef83754347a9397a

test:
  secret_key_base: f11737675931163875338d683af053e8f88c5f84d94ac47b0b0daed2b4a5704781f0a900eeab901d76d811bc146cc1a05537c56dca1024d2503c624a2a0604a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
